# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
      - script: |
          echo HELLO FROM Linux
          bash install.sh
          validORF ATGATGAAAAAAAAATAATTTATGCCCCCCCCCTAA
          echo $?
              

- job: macOS
  pool:
    vmImage: 'macOS-latest'
  steps:
      - script: |
            echo HELLO FROM MacOS
            bash install.sh
            validORF ATGATGAAAAAAAAATAATTTATGCCCCCCCCCTAA
            echo $?
              
             
- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
      - script: |
            echo HELLO FROM Windows
            bash install.sh
            validORF ATGATGAAAAAAAAATAATTTATGCCCCCCCCCTAA
            echo $?
